### ISSUE TITLE
Deadwood jedi's page doesn't allow data load from the plugin

### ISSUE THREAD

**Issue by 2f1k** [BryanCuneo/cb-calc-assistant#2] opened 2021-01-04 18:51 UTC
Hi thanks for your work.
It doesn't work since DWJ changes his site data.
Can you check this please ?
Thanks a lot

**Comment by cepedamarc** [comment] 2021-01-04 20:06
Duplicate of issue https://github.com/BryanCuneo/cb-calc-assistant/issues/1

**Closed as completed** 2021-02-16 04:43 UTC
